apiVersion: v1
kind: Service
metadata:
  name: {{ include "holy-synk.fullname" . }}
  labels:
    {{- include "holy-synk.labels" . | nindent 4 }}
    kubernetes.azure.com/generator: draft
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "holy-synk.selectorLabels" . | nindent 4 }}
